# hOM scRNA-seq analysis
# 
# in R (v4.0.5)#
library(dplyr)
library(magrittr)
library(Seurat)
#
library(ggplot2)
library(Polychrome)
library(ggbeeswarm)
library(ggthemes)
library(RColorBrewer)
library(scales)

# Read in CellRanger output #
organoid.data<-Read10X('./outs/filtered_feature_bc_matrix') #./outs/ is generated by CellRanger

# Create Seurat Object #
# Excluding genes expressed in less than 3 cells
organoid <- CreateSeuratObject(counts = organoid.data, project = 'MidOr', min.cells=3, min.features=200) 


# organoid
# An object of class Seurat 
# 25403 features across 14957 samples within 1 assay 
# Active assay: RNA (25403 features, 0 variable features)

################################
# Quality control #
# Assign additional feature of mitocondrial genes #
organoid[['percent.mt']] <- PercentageFeatureSet(organoid, pattern='^MT-')

# Subset dataset # 
# Excluding low-quality (nFeature_RNA < 1000), potential doublet (nFeature_RNA > 8000) and mitocondria-gene-elevated (percent.mt > 20) cells 
organoid.qc <- subset(organoid, subset = nFeature_RNA > 1000 & nFeature_RNA < 8000 & percent.mt < 20) 

# organoid.qc
# An object of class Seurat 
# 25403 features across 13361 samples within 1 assay 
# Active assay: RNA (25403 features, 0 variable features)

#################################
# Normalization #
organoid.qc.norm <- NormalizeData(organoid.qc, normalization.method = "LogNormalize", scale.factor = 10000)

# Find highly variable features
organoid.qc.norm.varf <- FindVariableFeatures(organoid.qc.norm, selection.method = "vst", nfeatures = 2000)
# Visualize top 10 genes
top10<-head(VariableFeatures(organoid.qc.norm.varf),10)
plot1<-VariableFeaturePlot(organoid.qc.norm.varf)
plot2<-LabelPoints(plot=plot1, points = top10, repel =T)
plot2

#################################
# Scaling / linear transformation 
allgene<-rownames(organoid.qc.norm.varf)
organoid.qc.norm.varf.scale <- ScaleData(organoid.qc.norm.varf, features=allgene)

# Linear dimensional reduction
organoid.qc.norm.varf.scale.pca <- RunPCA(organoid.qc.norm.varf.scale, features = VariableFeatures(object = organoid.qc.norm.varf.scale))
# Visualization
DimPlot(organoid.qc.norm.varf.scale.pca, reduction='pca')
DimHeatmap(organoid.qc.norm.varf.scale.pca, dims = 1, cells = 500, balanced = TRUE)

# Determine the dimensionality of the data
organoid.dim <- JackStraw(organoid.qc.norm.varf.scale.pca, num.replicate=100)
organoid.dim <- ScoreJackStraw(organoid.dim, dims = 1:20)

#################################
# Clustering
organoid.dim <- FindNeighbors(organoid.dim, dims = 1:20)
organoid.dim <- FindClusters(organoid.dim, resolution = 0.5)
# UMAP
organoid.umap <- RunUMAP(organoid.dim, dims = 1:20)
DimPlot(organoid.umap, reduction = "umap")

# save as tiff #
tiff('Seurat-mt20.tiff', units='in', width=10, height=10, res=600, compression ='lzw')
DimPlot(organoid.umap, reduction = "umap")
dev.off()

tiff('Seurat-mt20.label.tiff', units='in', width=10, height=10, res=600, compression ='lzw')
DimPlot(organoid.umap, reduction = "umap", label=T)
dev.off()

# UMAP by ggplot # Fig. 3A
orgg <- as.data.frame(Embeddings(organoid.umap, reduction = "umap"))
orgg$cluster <- organoid.umap@meta.data$seurat_clusters
identities <- levels(orgg$cluster)
my_color_palette <- hue_pal()(length(identities))

ggplot(data=orgg)+geom_point(aes(x=UMAP_1,y=UMAP_2, color=cluster), alpha=0.6,size=0.8)+scale_color_manual(values=my_color_palette)+theme_classic()
ggsave('./Fig3/total.tiff', wid=10, height=10)

#################################
# Find markers
organoid.marker <- FindAllMarkers(organoid.umap, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
# min.pct = 0.1 & logfc.threshold = 0.25 were selected from the references:
# e.g. 2021-07-23 SCIENCE paper: Heterogeneity of meningeal B cells reveals a lymphopoietic niche at the CNS borders

# Export the marker file as CSV #
write.csv(as.matrix(organoid.marker), file='./organoid.mt20.allmarkers.csv', quote=F)

# Heatmap of top 10 marker # fig. S7A
top10 <- organoid.marker %>% group_by(cluster) %>% top_n(n=10, wt =avg_log2FC)
write.csv(top10, './top10MarkerHeatmap.csv')

DoHeatmap(organoid.umap, features=top10$gene, slot='scale.data',label=F)
#ggsave('totalMarkerHeatmap.tiff', width=10, height=10)
ggsave('./FigS7/totalMarkerHeatmap.tiff', width=10, height=10, dpi=100)
ggsave('./FigS7/totalMarkerHeatmap.pdf', width=10, height=20, dpi=100)

#################################
# Save RDS
saveRDS(organoid.umap, file = "./organoid.mt20.umap.rds")

#################################

#################################
# Re-clustering analysis
 org <- readRDS('./organoid.mt20.umap.rds')

### Ectoderm ###
# Same workflow 
org.Ecto<-subset(org, idents=c(2,3,10,4,6,8,9,14,15,16,12,19))
org.Ecto$seurat_clusters_old <- org.Ecto$seurat_clusters

org.Ecto.norm <- NormalizeData(org.Ecto, normalization.method = "LogNormalize", scale.factor = 10000)
org.Ecto.norm.varf <- FindVariableFeatures(org.Ecto.norm, selection.method = "vst", nfeatures = 2000)
allgene<-rownames(org.Ecto.norm.varf)
org.Ecto.norm.varf.scale <- ScaleData(org.Ecto.norm.varf, features=allgene)

org.Ecto.norm.varf.scale.pca <- RunPCA(org.Ecto.norm.varf.scale, features = VariableFeatures(object = org.Ecto.norm.varf.scale))

#DimPlot(org.Ecto.norm.varf.scale.pca, reduction='pca')
#DimHeatmap(org.Ecto.norm.varf.scale.pca, dims = 1, cells = 500, balanced = TRUE)

# Determine the dimensionality of the data
org.Ecto.dim <- JackStraw(org.Ecto.norm.varf.scale.pca, num.replicate=100)
org.Ecto.dim <- ScoreJackStraw(org.Ecto.dim, dims = 1:20)

org.Ecto.dim <- FindNeighbors(org.Ecto.dim, dims = 1:20)
org.Ecto.dim <- FindClusters(org.Ecto.dim, resolution = 0.5)
# UMAP
org.Ecto.umap <- RunUMAP(org.Ecto.dim, dims = 1:20)

tiff('./org.ecto.tiff', units='in', width=10, height=10, res=600, compression ='lzw')
DimPlot(org.Ecto.umap, reduction = "umap", label=T)+NoLegend()
dev.off()

ecto.info <- data.frame(org.Ecto.umap@meta.data$seurat_clusters)
rownames(ecto.info) <- colnames(org.Ecto.umap)
names(ecto.info)[1] <- 'sub_cluster'
ecto.info$sub_cluster <- paste('Ecto', ecto.info$sub_cluster, sep='-')

org.Ecto.marker <- FindAllMarkers(org.Ecto.umap, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(as.matrix(org.Ecto.marker), file='./org.ecto.marker.csv', quote=F)
# Save RDS
saveRDS(org.Ecto.umap, file = "./org.Ecto.rds")

#####################################
# UMAP ggplot # fig. S8A
orgg <- as.data.frame(Embeddings(org.Ecto.umap, reduction = "umap"))
orgg$cluster <- org.Ecto.umap@meta.data$seurat_clusters
identities <- levels(orgg$cluster)
my_color_palette <- hue_pal()(length(identities))

ggplot(data=orgg)+geom_point(aes(x=UMAP_1,y=UMAP_2, color=cluster), alpha=0.5,size=1.5)+scale_color_manual(values=my_color_palette)+theme_classic()
ggsave('./FigS8/Endo.tiff', wid=10, height=10)


### Mesoderm + Endoderm ###
# Same workflow 
org.Mesendo<-subset(org, idents=c(0,1,5,11,13,7,18,17))

org.Mesendo.norm <- NormalizeData(org.Mesendo, normalization.method = "LogNormalize", scale.factor = 10000)
org.Mesendo.norm.varf <- FindVariableFeatures(org.Mesendo.norm, selection.method = "vst", nfeatures = 2000)
allgene<-rownames(org.Mesendo.norm.varf)
org.Mesendo.norm.varf.scale <- ScaleData(org.Mesendo.norm.varf, features=allgene)

org.Mesendo.norm.varf.scale.pca <- RunPCA(org.Mesendo.norm.varf.scale, features = VariableFeatures(object = org.Mesendo.norm.varf.scale))

#DimPlot(org.Mesendo.norm.varf.scale.pca, reduction='pca')
#DimHeatmap(org.Mesendo.norm.varf.scale.pca, dims = 1, cells = 500, balanced = TRUE)

# Determine the dimensionality of the data
org.Mesendo.dim <- JackStraw(org.Mesendo.norm.varf.scale.pca, num.replicate=100)
org.Mesendo.dim <- ScoreJackStraw(org.Mesendo.dim, dims = 1:20)

org.Mesendo.dim <- FindNeighbors(org.Mesendo.dim, dims = 1:20)
org.Mesendo.dim <- FindClusters(org.Mesendo.dim, resolution = 0.5)
# UMAP
org.Mesendo.umap <- RunUMAP(org.Mesendo.dim, dims = 1:20)

tiff('./org.Mesendo.tiff', units='in', width=10, height=10, res=600, compression ='lzw')
DimPlot(org.Mesendo.umap, reduction = "umap", label=T)+NoLegend()
dev.off()

mesendo.info <- data.frame(org.Mesendo.umap@meta.data$seurat_clusters)
rownames(mesendo.info) <- colnames(org.Mesendo.umap)
names(mesendo.info)[1] <- 'sub_cluster'
mesendo.info$sub_cluster <- paste('Mesendo', mesendo.info$sub_cluster, sep='-')

org.Mesendo.marker <- FindAllMarkers(org.Mesendo.umap, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(as.matrix(org.Mesendo.marker), file='./org.Mesendo.marker.csv', quote=F)
# Save RDS
saveRDS(org.Mesendo.umap, file = "./org.Mesendo.rds")

#####################################
# UMAP ggplot # fig. S9A
orgg <- as.data.frame(Embeddings(org.Mesendo.umap, reduction = "umap"))
orgg$cluster <- org.Mesendo.umap@meta.data$seurat_clusters
identities <- levels(orgg$cluster)
my_color_palette <- hue_pal()(length(identities))

ggplot(data=orgg)+geom_point(aes(x=UMAP_1,y=UMAP_2, color=cluster), alpha=0.5,size=1.5)+scale_color_manual(values=my_color_palette)+theme_classic()
ggsave('./FigS9/Mesendo.tiff', wid=10, height=10)


### Endoderm ###
# Same workflow 
org.Endo<-subset(org, idents=c(17))

org.Endo.norm <- NormalizeData(org.Endo, normalization.method = "LogNormalize", scale.factor = 10000)
org.Endo.norm.varf <- FindVariableFeatures(org.Endo.norm, selection.method = "vst", nfeatures = 2000)
allgene<-rownames(org.Endo.norm.varf)
org.Endo.norm.varf.scale <- ScaleData(org.Endo.norm.varf, features=allgene)

org.Endo.norm.varf.scale.pca <- RunPCA(org.Endo.norm.varf.scale, features = VariableFeatures(object = org.Endo.norm.varf.scale))

#DimPlot(org.Endo.norm.varf.scale.pca, reduction='pca')
#DimHeatmap(org.Endo.norm.varf.scale.pca, dims = 1, cells = 500, balanced = TRUE)

# Determine the dimensionality of the data
org.Endo.dim <- JackStraw(org.Endo.norm.varf.scale.pca, num.replicate=100)
org.Endo.dim <- ScoreJackStraw(org.Endo.dim, dims = 1:20)

org.Endo.dim <- FindNeighbors(org.Endo.dim, dims = 1:20)
org.Endo.dim <- FindClusters(org.Endo.dim, resolution = 0.5)
# UMAP
org.Endo.umap <- RunUMAP(org.Endo.dim, dims = 1:20)

tiff('./org.endo.tiff', units='in', width=10, height=10, res=600, compression ='lzw')
DimPlot(org.Endo.umap, reduction = "umap", label=T)+NoLegend()
dev.off()

endo.info <- data.frame(org.Endo.umap@meta.data$seurat_clusters)
rownames(endo.info) <- colnames(org.Endo.umap)
names(endo.info)[1] <- 'sub_cluster'
endo.info$sub_cluster <- paste('Endo', endo.info$sub_cluster, sep='-')

org.Endo.marker <- FindAllMarkers(org.Endo.umap, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(as.matrix(org.Endo.marker), file='./org.Endo.marker.csv', quote=F)
# Save RDS
saveRDS(org.Endo.umap, file = "./org.Endo.rds")

#####################################
# UMAP ggplot # fig. S9A
orgg <- as.data.frame(Embeddings(org.Endo.umap, reduction = "umap"))
orgg$cluster <- org.Endo.umap@meta.data$seurat_clusters
identities <- levels(orgg$cluster)
my_color_palette <- hue_pal()(length(identities))

ggplot(data=orgg)+geom_point(aes(x=UMAP_1,y=UMAP_2, color=cluster), alpha=0.5,size=1.5)+scale_color_manual(values=my_color_palette)+theme_classic()
ggsave('./FigS9/Endo.tiff', wid=10, height=10)


#################################
# Add sub-cluster meta-data
all.info <- rbind(ecto.info, mesendo.info)
all.info[row.names(endo.info),] <- endo.info$sub_cluster
org <- AddMetaData(org, metadata=all.info)
saveRDS(org, './organoid.mt20.umap.subclustered.rds')



















